#!/bin/bash
set -e

# Worktree initialization script
# Generates unique configuration for each git worktree to avoid conflicts

echo "=== Worktree Initialization ==="

# Get worktree information
WORKTREE_PATH=$(git rev-parse --show-toplevel)
WORKTREE_NAME=$(basename "$WORKTREE_PATH")
BRANCH_NAME=$(git branch --show-current)

echo "Worktree: $WORKTREE_NAME"
echo "Branch: $BRANCH_NAME"
echo ""

# Generate unique port offsets based on hash of worktree path
# This ensures consistent ports for the same worktree across restarts
HASH=$(echo -n "$WORKTREE_PATH" | md5sum 2>/dev/null | cut -c1-4 || echo -n "$WORKTREE_PATH" | md5 | cut -c1-4)
PORT_OFFSET=$((0x$HASH % 1000))

API_PORT=$((3000 + PORT_OFFSET))
WEB_PORT=$((5173 + PORT_OFFSET))

# Generate database name from branch (sanitized)
DB_NAME="ship_${BRANCH_NAME//[^a-zA-Z0-9]/_}"

echo "Generating configuration..."
echo "  API Port: $API_PORT"
echo "  Web Port: $WEB_PORT"
echo "  Database: $DB_NAME"
echo ""

# Create API .env.local
cat > api/.env.local << EOF
# Auto-generated by worktree-init.sh on $(date)
# Worktree: $WORKTREE_NAME
# Branch: $BRANCH_NAME

PORT=$API_PORT
NODE_ENV=development
DATABASE_URL=postgresql://localhost:5432/$DB_NAME
LOG_LEVEL=debug
CORS_ORIGIN=http://localhost:$WEB_PORT
EOF

# Create Web .env.local
cat > web/.env.local << EOF
# Auto-generated by worktree-init.sh on $(date)
# Worktree: $WORKTREE_NAME
# Branch: $BRANCH_NAME

VITE_API_URL=http://localhost:$API_PORT
VITE_PORT=$WEB_PORT
EOF

echo "Configuration files created:"
echo "  - api/.env.local"
echo "  - web/.env.local"
echo ""

# Check if database exists, create if not
if command -v psql &> /dev/null; then
  echo "Checking database..."
  if psql -U postgres -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    echo "  Database '$DB_NAME' already exists"
  else
    echo "  Creating database '$DB_NAME'..."
    psql -U postgres -c "CREATE DATABASE $DB_NAME;" || {
      echo "  Warning: Failed to create database (you may need to run this manually)"
    }
  fi
else
  echo "psql not found - skipping database creation"
  echo "You'll need to manually create database: $DB_NAME"
fi

echo ""
echo "=== Initialization Complete ==="
echo ""
echo "Next steps:"
echo "  1. pnpm install"
echo "  2. pnpm run dev"
echo ""
echo "Your servers will run on:"
echo "  API: http://localhost:$API_PORT"
echo "  Web: http://localhost:$WEB_PORT"
