#!/usr/bin/env node
// Runs eslint with the type-safety config across the monorepo and writes a
// baseline to audit/type-safety/baseline/. Produces:
//
//   baseline/raw.json    — full eslint JSON output (per-file messages)
//   baseline/summary.md  — human-readable counts (by rule, by package, top files)
//
// The point: replace count.sh as the source of truth. The regex script
// under-counted non-null assertions ~2.5x and can't see no-unsafe-* propagation.

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const outDir = resolve(__dirname, 'baseline');
mkdirSync(outDir, { recursive: true });

console.error('Running eslint (type-aware, this takes a few minutes)...');

let rawJson;
try {
  rawJson = execFileSync(
    'npx',
    ['eslint', '.', '--format', 'json'],
    { cwd: repoRoot, maxBuffer: 256 * 1024 * 1024, stdio: ['ignore', 'pipe', 'inherit'] },
  ).toString();
} catch (err) {
  // eslint exits non-zero when there are findings; stdout still holds the JSON.
  if (err.stdout) {
    rawJson = err.stdout.toString();
  } else {
    throw err;
  }
}

const results = JSON.parse(rawJson);
writeFileSync(resolve(outDir, 'raw.json'), rawJson);

const byRule = new Map();
const byPackage = new Map();
const byFile = new Map();

const packageOf = (absPath) => {
  const rel = relative(repoRoot, absPath);
  const top = rel.split('/')[0];
  return ['api', 'web', 'shared', 'e2e'].includes(top) ? top : 'other';
};

for (const file of results) {
  if (!file.messages.length) continue;
  const pkg = packageOf(file.filePath);
  const relPath = relative(repoRoot, file.filePath);

  for (const msg of file.messages) {
    const rule = msg.ruleId ?? '(parse-error)';

    byRule.set(rule, (byRule.get(rule) ?? 0) + 1);

    if (!byPackage.has(pkg)) byPackage.set(pkg, new Map());
    const pkgRules = byPackage.get(pkg);
    pkgRules.set(rule, (pkgRules.get(rule) ?? 0) + 1);

    byFile.set(relPath, (byFile.get(relPath) ?? 0) + 1);
  }
}

const total = [...byRule.values()].reduce((a, b) => a + b, 0);

const sortDesc = (m) => [...m.entries()].sort((a, b) => b[1] - a[1]);

const ruleLines = sortDesc(byRule).map(([r, n]) => `| \`${r}\` | ${n} |`).join('\n');

const packages = ['api', 'web', 'shared', 'e2e'];
const allRules = sortDesc(byRule).map(([r]) => r);
const pkgHeader = `| Rule | ${packages.join(' | ')} |`;
const pkgSep = `|---|${packages.map(() => '---:').join('|')}|`;
const pkgRows = allRules.map((rule) => {
  const cells = packages.map((p) => byPackage.get(p)?.get(rule) ?? 0);
  return `| \`${rule}\` | ${cells.join(' | ')} |`;
}).join('\n');

const topFiles = sortDesc(byFile).slice(0, 20)
  .map(([f, n], i) => `| ${i + 1} | \`${f}\` | ${n} |`).join('\n');

const summary = `# Type-Safety Lint Baseline

Generated by \`audit/type-safety/lint-report.mjs\` (eslint + typescript-eslint, type-aware).

**Total warnings:** ${total}

## By rule

| Rule | Count |
|---|---:|
${ruleLines}

## By rule × package

${pkgHeader}
${pkgSep}
${pkgRows}

## Top 20 files

| Rank | File | Warnings |
|---|---|---:|
${topFiles}

## Notes

- These counts replace the regex-based numbers in \`audit/type-safety/README.md\`.
- The peer review predicted non-null assertions were ~2.5× under-counted by the regex; \`no-non-null-assertion\` here is the authoritative count.
- \`no-unsafe-*\` rules count downstream consequences of \`any\` (e.g. \`row.x\` access where \`row: any\`). Fixing one \`any\` at a boundary collapses many of these.
- Reduction targets in remediation PRs should track \`no-explicit-any\`, \`no-non-null-assertion\`, and \`no-unsafe-*\` separately — they have different costs and meanings.
`;

writeFileSync(resolve(outDir, 'summary.md'), summary);

console.error(`Wrote ${resolve(outDir, 'raw.json')}`);
console.error(`Wrote ${resolve(outDir, 'summary.md')}`);
console.error(`Total warnings: ${total}`);
